server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true

security:
  user:
    password: password